services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wello_app
    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wello_backend
    ports:
      - "8000:8000"
    environment:
      DB_NAME: wello_db
      DB_USER: wello_dev
      DB_PASSWORD: Wello@2910
      DB_HOST: db
      DB_PORT: 3306
      JWT_SECRET: 5c8c8f3b6d3f962cfe476b7e14f9cb0055d66087f588c8fb56664ef0002bd560
      OPEN_AI_KEY: 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
      EMAIL_USERNAME: 'abanoubsamy2341@gmail.com'
      EMAIL_PASSWORD: 'uyod qtbz youi xhkc'
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_PORT: 587

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.44
    container_name: wello_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wello_db
      MYSQL_USER: wello_dev
      MYSQL_PASSWORD: Wello@2910

    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
